defaults:
  - _self_
  - model: solar
  - train: train
  - logger: wandb

seed: 42
mode: "train"  # "train" 또는 "inference"

data:
  train_path: "./data/train.csv"
  valid_path: "./data/dev.csv" 
  test_path: "./data/test.csv"
  sample_submission_path : "./data/sample_submission.csv"
  submission_path : "./data/submission.csv"

path:
  pretrained_path: "whbye-choi/OPEN-SOLAR-KO-10.7B-exp"
